[package]
name = "putzen-cli"
description = "helps keeping your disk clean of build and dependency artifacts safely"
version = "1.0.0"
authors = ["Sven Assmann <sven.assmann.it@gmail.com>"]
edition = "2021"
license = "GPL-3.0-only"
readme = "README.md"
keywords = ["commandline", "cleanup"]
categories = ["command-line-utilities"]
repository = "https://github.com/sassman/putzen-rs"
exclude = [".github/*", ".ci/*" ,".gitignore"]

[dependencies]
argh = "0.1"
dialoguer = "0.9"
jwalk = "0.6"

[[bin]]
name = "putzen"
path = "src/bin/putzen.rs"
