[package]
name = "putzen-cli"
description = "help keeping your disk clean of build and dependency artifacts"
version = "0.0.1"
authors = ["Sven Assmann <sven.assmann.it@gmail.com>"]
edition = "2021"
license = "GPL-3.0-only"
readme = "README.md"
keywords = ["commandline", "cleanup"]
categories = ["command-line-utilities"]
repository = "https://github.com/sassman/putzen-rs"
exclude = [".github/*", ".ci/*" ,".gitignore"]

[dependencies]
argh = "0.1"
jwalk = "0.6"

[[bin]]
name = "putzen"
path = "src/bin/putzen.rs"